#!/usr/bin/env bash
#Displays numbers 1 to 100, but displays FizzBuzz when its a multiple of 3 and 5, Fizz on multiples of 3, Buzz on multiples of 5.
N=1
while [ $N -lt 101 ]
do
	if [ $((N % 5)) == 0 ] && [ $((N % 3)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((N % 5)) == 0 ]
	then
		echo "Buzz"
	elif [ $((N % 3)) == 0 ]
	then
		echo "Fizz"
	else
		echo "$N"
	fi	
	((N+=1))
done
