#!/usr/bin/env bash
#Loops "Best School" 10 times, but it displays Best School and then Hi on a new line.
counter=0
while [ "$counter" -lt 10 ]
do
      echo "Best School"
      ((counter=counter+1))
if [ $counter -eq 9 ]
then
      echo "Hi"
fi
done
