#!/usr/bin/env bash
#Loops from 1 to 10 and displays bad luck on the 4th iteration, good luck on the 8th, Best School on the rest iterations
counter=0
while [ "$counter" -lt 10 ]
do
        ((counter=counter+1))

   if [ $counter -eq 4 ]
   then

        echo "bad luck"

   elif [ $counter -eq 8 ]
   then

        echo 'good luck'

   else

        echo 'Best School'

fi
done

