#!/usr/bin/env bash
#Loops from 1 to 20 and displays bad luck from China on the 4th iteration, bad luck from Japan on the 9th, bad luck from Italy on the 17th, Best School on the rest iterations
counter=1
while [ "$counter" -lt 20 ]
do
	echo "$counter"
      case "$counter" in
	       "4") echo "bad luck from China";;
	       "9") echo "bad luck from Japan";;
	       "17") echo "bad luck from Italy";;
      esac
      ((counter=counter+1))
done

