#!/usr/bin/env bash
#Gives information about the school file
Found=0
for file in *
do

	if [ "$file" == "school" ]
	then
		((Found=1))
		echo "school file exists"
		if [ -s "$file" ]
		then

			echo "school file is not empty"

		else

			echo "school file is empty"

		fi

		if [ -f "$file" ]
		then

			echo "school is a regular file"

		fi

	fi

done

if [ $Found -eq 0 ]
then

	echo "school file does not exist"
fi
