#!/usr/bin/env bash
#Displays the time for 12 hours and 59 minutes.
m=1
h=1
while [ "$m" -lt 60 ]
do
      echo "$m"
      if [ "$m" -eq 59 ]
      then
	      echo "Hour: $h"
	      m=0
      elif [ "$h" -eq 12 | "$m" -eq 59 ]
      then 
              break
      fi
      ((m++))
      ((h=h+1))
done
