#!/usr/bin/env bash
#Creates the file "/var/run/myscript.pid", displays "To infinity and beyond", "I hate the kill command" when recieving SIGTERM signal, "Y U no love me?!" when recieving SIGINT signal, and deletes the file "/var/run/myscript.pid and terminates itself when recieving a SIGQUIT or SIGTERM signal.
sudo touch /var/run/myscript.pid
sudo bash -c 'echo $$ > /var/run/myscript.pid'
while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I hate the kill command"; sudo rm /var/run/myscript.pid' SIGTERM
	trap  'echo "Y U no love me?!"' SIGINT
	trap 'sudo rm /var/run/myscript.pid' SIGQUIT
done
