#!/usr/bin/env bash
#Displays "To infinity and beyond" with a sleep 2 in between iterations, and displays "I am invinsible!!!" when recieving a SIGTERM signal.
while true
do 
	echo "To infinity and beyond"
	sleep 2
	trap  'echo "I am invincible!!!"' SIGTERM
done
